package com.w00tmast3r.skquery.skript;

public class DummyClasses {

    public static abstract class DummyBase {
        protected String value;

        public String getValue() {
            return value;
        }

        public void setValue(String value) {
            this.value = value;
        }

        @Override
        public String toString() {
            return value;
        }

        @Override
        public boolean equals(Object o) {
            if (this == o) return true;
            if (!(o instanceof DummyBase)) return false;
            DummyBase dummyBase = (DummyBase) o;
            return value.equals(dummyBase.value);

        }

        @Override
        public int hashCode() {
            return value.hashCode();
        }
    }

    public static class _1 extends DummyBase {}
    public static class _2 extends DummyBase {}
    public static class _3 extends DummyBase {}
    public static class _4 extends DummyBase {}
    public static class _5 extends DummyBase {}
    public static class _6 extends DummyBase {}
    public static class _7 extends DummyBase {}
    public static class _8 extends DummyBase {}
    public static class _9 extends DummyBase {}
    public static class _10 extends DummyBase {}
    public static class _11 extends DummyBase {}
    public static class _12 extends DummyBase {}
    public static class _13 extends DummyBase {}
    public static class _14 extends DummyBase {}
    public static class _15 extends DummyBase {}
    public static class _16 extends DummyBase {}
    public static class _17 extends DummyBase {}
    public static class _18 extends DummyBase {}
    public static class _19 extends DummyBase {}
    public static class _20 extends DummyBase {}
    public static class _21 extends DummyBase {}
    public static class _22 extends DummyBase {}
    public static class _23 extends DummyBase {}
    public static class _24 extends DummyBase {}
    public static class _25 extends DummyBase {}
    public static class _26 extends DummyBase {}
    public static class _27 extends DummyBase {}
    public static class _28 extends DummyBase {}
    public static class _29 extends DummyBase {}
    public static class _30 extends DummyBase {}
    public static class _31 extends DummyBase {}
    public static class _32 extends DummyBase {}
    public static class _33 extends DummyBase {}
    public static class _34 extends DummyBase {}
    public static class _35 extends DummyBase {}
    public static class _36 extends DummyBase {}
    public static class _37 extends DummyBase {}
    public static class _38 extends DummyBase {}
    public static class _39 extends DummyBase {}
    public static class _40 extends DummyBase {}
    public static class _41 extends DummyBase {}
    public static class _42 extends DummyBase {}
    public static class _43 extends DummyBase {}
    public static class _44 extends DummyBase {}
    public static class _45 extends DummyBase {}
    public static class _46 extends DummyBase {}
    public static class _47 extends DummyBase {}
    public static class _48 extends DummyBase {}
    public static class _49 extends DummyBase {}
    public static class _50 extends DummyBase {}
    public static class _51 extends DummyBase {}
    public static class _52 extends DummyBase {}
    public static class _53 extends DummyBase {}
    public static class _54 extends DummyBase {}
    public static class _55 extends DummyBase {}
    public static class _56 extends DummyBase {}
    public static class _57 extends DummyBase {}
    public static class _58 extends DummyBase {}
    public static class _59 extends DummyBase {}
    public static class _60 extends DummyBase {}
    public static class _61 extends DummyBase {}
    public static class _62 extends DummyBase {}
    public static class _63 extends DummyBase {}
    public static class _64 extends DummyBase {}
    public static class _65 extends DummyBase {}
    public static class _66 extends DummyBase {}
    public static class _67 extends DummyBase {}
    public static class _68 extends DummyBase {}
    public static class _69 extends DummyBase {}
    public static class _70 extends DummyBase {}
    public static class _71 extends DummyBase {}
    public static class _72 extends DummyBase {}
    public static class _73 extends DummyBase {}
    public static class _74 extends DummyBase {}
    public static class _75 extends DummyBase {}
    public static class _76 extends DummyBase {}
    public static class _77 extends DummyBase {}
    public static class _78 extends DummyBase {}
    public static class _79 extends DummyBase {}
    public static class _80 extends DummyBase {}
    public static class _81 extends DummyBase {}
    public static class _82 extends DummyBase {}
    public static class _83 extends DummyBase {}
    public static class _84 extends DummyBase {}
    public static class _85 extends DummyBase {}
    public static class _86 extends DummyBase {}
    public static class _87 extends DummyBase {}
    public static class _88 extends DummyBase {}
    public static class _89 extends DummyBase {}
    public static class _90 extends DummyBase {}
    public static class _91 extends DummyBase {}
    public static class _92 extends DummyBase {}
    public static class _93 extends DummyBase {}
    public static class _94 extends DummyBase {}
    public static class _95 extends DummyBase {}
    public static class _96 extends DummyBase {}
    public static class _97 extends DummyBase {}
    public static class _98 extends DummyBase {}
    public static class _99 extends DummyBase {}
    public static class _100 extends DummyBase {}
    public static class _101 extends DummyBase {}
    public static class _102 extends DummyBase {}
    public static class _103 extends DummyBase {}
    public static class _104 extends DummyBase {}
    public static class _105 extends DummyBase {}
    public static class _106 extends DummyBase {}
    public static class _107 extends DummyBase {}
    public static class _108 extends DummyBase {}
    public static class _109 extends DummyBase {}
    public static class _110 extends DummyBase {}
    public static class _111 extends DummyBase {}
    public static class _112 extends DummyBase {}
    public static class _113 extends DummyBase {}
    public static class _114 extends DummyBase {}
    public static class _115 extends DummyBase {}
    public static class _116 extends DummyBase {}
    public static class _117 extends DummyBase {}
    public static class _118 extends DummyBase {}
    public static class _119 extends DummyBase {}
    public static class _120 extends DummyBase {}
    public static class _121 extends DummyBase {}
    public static class _122 extends DummyBase {}
    public static class _123 extends DummyBase {}
    public static class _124 extends DummyBase {}
    public static class _125 extends DummyBase {}
    public static class _126 extends DummyBase {}
    public static class _127 extends DummyBase {}
    public static class _128 extends DummyBase {}
    public static class _129 extends DummyBase {}
    public static class _130 extends DummyBase {}
    public static class _131 extends DummyBase {}
    public static class _132 extends DummyBase {}
    public static class _133 extends DummyBase {}
    public static class _134 extends DummyBase {}
    public static class _135 extends DummyBase {}
    public static class _136 extends DummyBase {}
    public static class _137 extends DummyBase {}
    public static class _138 extends DummyBase {}
    public static class _139 extends DummyBase {}
    public static class _140 extends DummyBase {}
    public static class _141 extends DummyBase {}
    public static class _142 extends DummyBase {}
    public static class _143 extends DummyBase {}
    public static class _144 extends DummyBase {}
    public static class _145 extends DummyBase {}
    public static class _146 extends DummyBase {}
    public static class _147 extends DummyBase {}
    public static class _148 extends DummyBase {}
    public static class _149 extends DummyBase {}
    public static class _150 extends DummyBase {}
    public static class _151 extends DummyBase {}
    public static class _152 extends DummyBase {}
    public static class _153 extends DummyBase {}
    public static class _154 extends DummyBase {}
    public static class _155 extends DummyBase {}
    public static class _156 extends DummyBase {}
    public static class _157 extends DummyBase {}
    public static class _158 extends DummyBase {}
    public static class _159 extends DummyBase {}
    public static class _160 extends DummyBase {}
    public static class _161 extends DummyBase {}
    public static class _162 extends DummyBase {}
    public static class _163 extends DummyBase {}
    public static class _164 extends DummyBase {}
    public static class _165 extends DummyBase {}
    public static class _166 extends DummyBase {}
    public static class _167 extends DummyBase {}
    public static class _168 extends DummyBase {}
    public static class _169 extends DummyBase {}
    public static class _170 extends DummyBase {}
    public static class _171 extends DummyBase {}
    public static class _172 extends DummyBase {}
    public static class _173 extends DummyBase {}
    public static class _174 extends DummyBase {}
    public static class _175 extends DummyBase {}
    public static class _176 extends DummyBase {}
    public static class _177 extends DummyBase {}
    public static class _178 extends DummyBase {}
    public static class _179 extends DummyBase {}
    public static class _180 extends DummyBase {}
    public static class _181 extends DummyBase {}
    public static class _182 extends DummyBase {}
    public static class _183 extends DummyBase {}
    public static class _184 extends DummyBase {}
    public static class _185 extends DummyBase {}
    public static class _186 extends DummyBase {}
    public static class _187 extends DummyBase {}
    public static class _188 extends DummyBase {}
    public static class _189 extends DummyBase {}
    public static class _190 extends DummyBase {}
    public static class _191 extends DummyBase {}
    public static class _192 extends DummyBase {}
    public static class _193 extends DummyBase {}
    public static class _194 extends DummyBase {}
    public static class _195 extends DummyBase {}
    public static class _196 extends DummyBase {}
    public static class _197 extends DummyBase {}
    public static class _198 extends DummyBase {}
    public static class _199 extends DummyBase {}
    public static class _200 extends DummyBase {}
    public static class _201 extends DummyBase {}
    public static class _202 extends DummyBase {}
    public static class _203 extends DummyBase {}
    public static class _204 extends DummyBase {}
    public static class _205 extends DummyBase {}
    public static class _206 extends DummyBase {}
    public static class _207 extends DummyBase {}
    public static class _208 extends DummyBase {}
    public static class _209 extends DummyBase {}
    public static class _210 extends DummyBase {}
    public static class _211 extends DummyBase {}
    public static class _212 extends DummyBase {}
    public static class _213 extends DummyBase {}
    public static class _214 extends DummyBase {}
    public static class _215 extends DummyBase {}
    public static class _216 extends DummyBase {}
    public static class _217 extends DummyBase {}
    public static class _218 extends DummyBase {}
    public static class _219 extends DummyBase {}
    public static class _220 extends DummyBase {}
    public static class _221 extends DummyBase {}
    public static class _222 extends DummyBase {}
    public static class _223 extends DummyBase {}
    public static class _224 extends DummyBase {}
    public static class _225 extends DummyBase {}
    public static class _226 extends DummyBase {}
    public static class _227 extends DummyBase {}
    public static class _228 extends DummyBase {}
    public static class _229 extends DummyBase {}
    public static class _230 extends DummyBase {}
    public static class _231 extends DummyBase {}
    public static class _232 extends DummyBase {}
    public static class _233 extends DummyBase {}
    public static class _234 extends DummyBase {}
    public static class _235 extends DummyBase {}
    public static class _236 extends DummyBase {}
    public static class _237 extends DummyBase {}
    public static class _238 extends DummyBase {}
    public static class _239 extends DummyBase {}
    public static class _240 extends DummyBase {}
    public static class _241 extends DummyBase {}
    public static class _242 extends DummyBase {}
    public static class _243 extends DummyBase {}
    public static class _244 extends DummyBase {}
    public static class _245 extends DummyBase {}
    public static class _246 extends DummyBase {}
    public static class _247 extends DummyBase {}
    public static class _248 extends DummyBase {}
    public static class _249 extends DummyBase {}
    public static class _250 extends DummyBase {}
    public static class _251 extends DummyBase {}
    public static class _252 extends DummyBase {}
    public static class _253 extends DummyBase {}
    public static class _254 extends DummyBase {}
    public static class _255 extends DummyBase {}
    public static class _256 extends DummyBase {}
    public static class _257 extends DummyBase {}
    public static class _258 extends DummyBase {}
    public static class _259 extends DummyBase {}
    public static class _260 extends DummyBase {}
    public static class _261 extends DummyBase {}
    public static class _262 extends DummyBase {}
    public static class _263 extends DummyBase {}
    public static class _264 extends DummyBase {}
    public static class _265 extends DummyBase {}
    public static class _266 extends DummyBase {}
    public static class _267 extends DummyBase {}
    public static class _268 extends DummyBase {}
    public static class _269 extends DummyBase {}
    public static class _270 extends DummyBase {}
    public static class _271 extends DummyBase {}
    public static class _272 extends DummyBase {}
    public static class _273 extends DummyBase {}
    public static class _274 extends DummyBase {}
    public static class _275 extends DummyBase {}
    public static class _276 extends DummyBase {}
    public static class _277 extends DummyBase {}
    public static class _278 extends DummyBase {}
    public static class _279 extends DummyBase {}
    public static class _280 extends DummyBase {}
    public static class _281 extends DummyBase {}
    public static class _282 extends DummyBase {}
    public static class _283 extends DummyBase {}
    public static class _284 extends DummyBase {}
    public static class _285 extends DummyBase {}
    public static class _286 extends DummyBase {}
    public static class _287 extends DummyBase {}
    public static class _288 extends DummyBase {}
    public static class _289 extends DummyBase {}
    public static class _290 extends DummyBase {}
    public static class _291 extends DummyBase {}
    public static class _292 extends DummyBase {}
    public static class _293 extends DummyBase {}
    public static class _294 extends DummyBase {}
    public static class _295 extends DummyBase {}
    public static class _296 extends DummyBase {}
    public static class _297 extends DummyBase {}
    public static class _298 extends DummyBase {}
    public static class _299 extends DummyBase {}
    public static class _300 extends DummyBase {}
    public static class _301 extends DummyBase {}
    public static class _302 extends DummyBase {}
    public static class _303 extends DummyBase {}
    public static class _304 extends DummyBase {}
    public static class _305 extends DummyBase {}
    public static class _306 extends DummyBase {}
    public static class _307 extends DummyBase {}
    public static class _308 extends DummyBase {}
    public static class _309 extends DummyBase {}
    public static class _310 extends DummyBase {}
    public static class _311 extends DummyBase {}
    public static class _312 extends DummyBase {}
    public static class _313 extends DummyBase {}
    public static class _314 extends DummyBase {}
    public static class _315 extends DummyBase {}
    public static class _316 extends DummyBase {}
    public static class _317 extends DummyBase {}
    public static class _318 extends DummyBase {}
    public static class _319 extends DummyBase {}
    public static class _320 extends DummyBase {}
    public static class _321 extends DummyBase {}
    public static class _322 extends DummyBase {}
    public static class _323 extends DummyBase {}
    public static class _324 extends DummyBase {}
    public static class _325 extends DummyBase {}
    public static class _326 extends DummyBase {}
    public static class _327 extends DummyBase {}
    public static class _328 extends DummyBase {}
    public static class _329 extends DummyBase {}
    public static class _330 extends DummyBase {}
    public static class _331 extends DummyBase {}
    public static class _332 extends DummyBase {}
    public static class _333 extends DummyBase {}
    public static class _334 extends DummyBase {}
    public static class _335 extends DummyBase {}
    public static class _336 extends DummyBase {}
    public static class _337 extends DummyBase {}
    public static class _338 extends DummyBase {}
    public static class _339 extends DummyBase {}
    public static class _340 extends DummyBase {}
    public static class _341 extends DummyBase {}
    public static class _342 extends DummyBase {}
    public static class _343 extends DummyBase {}
    public static class _344 extends DummyBase {}
    public static class _345 extends DummyBase {}
    public static class _346 extends DummyBase {}
    public static class _347 extends DummyBase {}
    public static class _348 extends DummyBase {}
    public static class _349 extends DummyBase {}
    public static class _350 extends DummyBase {}
    public static class _351 extends DummyBase {}
    public static class _352 extends DummyBase {}
    public static class _353 extends DummyBase {}
    public static class _354 extends DummyBase {}
    public static class _355 extends DummyBase {}
    public static class _356 extends DummyBase {}
    public static class _357 extends DummyBase {}
    public static class _358 extends DummyBase {}
    public static class _359 extends DummyBase {}
    public static class _360 extends DummyBase {}
    public static class _361 extends DummyBase {}
    public static class _362 extends DummyBase {}
    public static class _363 extends DummyBase {}
    public static class _364 extends DummyBase {}
    public static class _365 extends DummyBase {}
    public static class _366 extends DummyBase {}
    public static class _367 extends DummyBase {}
    public static class _368 extends DummyBase {}
    public static class _369 extends DummyBase {}
    public static class _370 extends DummyBase {}
    public static class _371 extends DummyBase {}
    public static class _372 extends DummyBase {}
    public static class _373 extends DummyBase {}
    public static class _374 extends DummyBase {}
    public static class _375 extends DummyBase {}
    public static class _376 extends DummyBase {}
    public static class _377 extends DummyBase {}
    public static class _378 extends DummyBase {}
    public static class _379 extends DummyBase {}
    public static class _380 extends DummyBase {}
    public static class _381 extends DummyBase {}
    public static class _382 extends DummyBase {}
    public static class _383 extends DummyBase {}
    public static class _384 extends DummyBase {}
    public static class _385 extends DummyBase {}
    public static class _386 extends DummyBase {}
    public static class _387 extends DummyBase {}
    public static class _388 extends DummyBase {}
    public static class _389 extends DummyBase {}
    public static class _390 extends DummyBase {}
    public static class _391 extends DummyBase {}
    public static class _392 extends DummyBase {}
    public static class _393 extends DummyBase {}
    public static class _394 extends DummyBase {}
    public static class _395 extends DummyBase {}
    public static class _396 extends DummyBase {}
    public static class _397 extends DummyBase {}
    public static class _398 extends DummyBase {}
    public static class _399 extends DummyBase {}
    public static class _400 extends DummyBase {}
    public static class _401 extends DummyBase {}
    public static class _402 extends DummyBase {}
    public static class _403 extends DummyBase {}
    public static class _404 extends DummyBase {}
    public static class _405 extends DummyBase {}
    public static class _406 extends DummyBase {}
    public static class _407 extends DummyBase {}
    public static class _408 extends DummyBase {}
    public static class _409 extends DummyBase {}
    public static class _410 extends DummyBase {}
    public static class _411 extends DummyBase {}
    public static class _412 extends DummyBase {}
    public static class _413 extends DummyBase {}
    public static class _414 extends DummyBase {}
    public static class _415 extends DummyBase {}
    public static class _416 extends DummyBase {}
    public static class _417 extends DummyBase {}
    public static class _418 extends DummyBase {}
    public static class _419 extends DummyBase {}
    public static class _420 extends DummyBase {}
    public static class _421 extends DummyBase {}
    public static class _422 extends DummyBase {}
    public static class _423 extends DummyBase {}
    public static class _424 extends DummyBase {}
    public static class _425 extends DummyBase {}
    public static class _426 extends DummyBase {}
    public static class _427 extends DummyBase {}
    public static class _428 extends DummyBase {}
    public static class _429 extends DummyBase {}
    public static class _430 extends DummyBase {}
    public static class _431 extends DummyBase {}
    public static class _432 extends DummyBase {}
    public static class _433 extends DummyBase {}
    public static class _434 extends DummyBase {}
    public static class _435 extends DummyBase {}
    public static class _436 extends DummyBase {}
    public static class _437 extends DummyBase {}
    public static class _438 extends DummyBase {}
    public static class _439 extends DummyBase {}
    public static class _440 extends DummyBase {}
    public static class _441 extends DummyBase {}
    public static class _442 extends DummyBase {}
    public static class _443 extends DummyBase {}
    public static class _444 extends DummyBase {}
    public static class _445 extends DummyBase {}
    public static class _446 extends DummyBase {}
    public static class _447 extends DummyBase {}
    public static class _448 extends DummyBase {}
    public static class _449 extends DummyBase {}
    public static class _450 extends DummyBase {}
    public static class _451 extends DummyBase {}
    public static class _452 extends DummyBase {}
    public static class _453 extends DummyBase {}
    public static class _454 extends DummyBase {}
    public static class _455 extends DummyBase {}
    public static class _456 extends DummyBase {}
    public static class _457 extends DummyBase {}
    public static class _458 extends DummyBase {}
    public static class _459 extends DummyBase {}
    public static class _460 extends DummyBase {}
    public static class _461 extends DummyBase {}
    public static class _462 extends DummyBase {}
    public static class _463 extends DummyBase {}
    public static class _464 extends DummyBase {}
    public static class _465 extends DummyBase {}
    public static class _466 extends DummyBase {}
    public static class _467 extends DummyBase {}
    public static class _468 extends DummyBase {}
    public static class _469 extends DummyBase {}
    public static class _470 extends DummyBase {}
    public static class _471 extends DummyBase {}
    public static class _472 extends DummyBase {}
    public static class _473 extends DummyBase {}
    public static class _474 extends DummyBase {}
    public static class _475 extends DummyBase {}
    public static class _476 extends DummyBase {}
    public static class _477 extends DummyBase {}
    public static class _478 extends DummyBase {}
    public static class _479 extends DummyBase {}
    public static class _480 extends DummyBase {}
    public static class _481 extends DummyBase {}
    public static class _482 extends DummyBase {}
    public static class _483 extends DummyBase {}
    public static class _484 extends DummyBase {}
    public static class _485 extends DummyBase {}
    public static class _486 extends DummyBase {}
    public static class _487 extends DummyBase {}
    public static class _488 extends DummyBase {}
    public static class _489 extends DummyBase {}
    public static class _490 extends DummyBase {}
    public static class _491 extends DummyBase {}
    public static class _492 extends DummyBase {}
    public static class _493 extends DummyBase {}
    public static class _494 extends DummyBase {}
    public static class _495 extends DummyBase {}
    public static class _496 extends DummyBase {}
    public static class _497 extends DummyBase {}
    public static class _498 extends DummyBase {}
    public static class _499 extends DummyBase {}
    public static class _500 extends DummyBase {}
    public static class _501 extends DummyBase {}
    public static class _502 extends DummyBase {}
    public static class _503 extends DummyBase {}
    public static class _504 extends DummyBase {}
    public static class _505 extends DummyBase {}
    public static class _506 extends DummyBase {}
    public static class _507 extends DummyBase {}
    public static class _508 extends DummyBase {}
    public static class _509 extends DummyBase {}
    public static class _510 extends DummyBase {}
    public static class _511 extends DummyBase {}
    public static class _512 extends DummyBase {}
    public static class _513 extends DummyBase {}
    public static class _514 extends DummyBase {}
    public static class _515 extends DummyBase {}
    public static class _516 extends DummyBase {}
    public static class _517 extends DummyBase {}
    public static class _518 extends DummyBase {}
    public static class _519 extends DummyBase {}
    public static class _520 extends DummyBase {}
    public static class _521 extends DummyBase {}
    public static class _522 extends DummyBase {}
    public static class _523 extends DummyBase {}
    public static class _524 extends DummyBase {}
    public static class _525 extends DummyBase {}
    public static class _526 extends DummyBase {}
    public static class _527 extends DummyBase {}
    public static class _528 extends DummyBase {}
    public static class _529 extends DummyBase {}
    public static class _530 extends DummyBase {}
    public static class _531 extends DummyBase {}
    public static class _532 extends DummyBase {}
    public static class _533 extends DummyBase {}
    public static class _534 extends DummyBase {}
    public static class _535 extends DummyBase {}
    public static class _536 extends DummyBase {}
    public static class _537 extends DummyBase {}
    public static class _538 extends DummyBase {}
    public static class _539 extends DummyBase {}
    public static class _540 extends DummyBase {}
    public static class _541 extends DummyBase {}
    public static class _542 extends DummyBase {}
    public static class _543 extends DummyBase {}
    public static class _544 extends DummyBase {}
    public static class _545 extends DummyBase {}
    public static class _546 extends DummyBase {}
    public static class _547 extends DummyBase {}
    public static class _548 extends DummyBase {}
    public static class _549 extends DummyBase {}
    public static class _550 extends DummyBase {}
    public static class _551 extends DummyBase {}
    public static class _552 extends DummyBase {}
    public static class _553 extends DummyBase {}
    public static class _554 extends DummyBase {}
    public static class _555 extends DummyBase {}
    public static class _556 extends DummyBase {}
    public static class _557 extends DummyBase {}
    public static class _558 extends DummyBase {}
    public static class _559 extends DummyBase {}
    public static class _560 extends DummyBase {}
    public static class _561 extends DummyBase {}
    public static class _562 extends DummyBase {}
    public static class _563 extends DummyBase {}
    public static class _564 extends DummyBase {}
    public static class _565 extends DummyBase {}
    public static class _566 extends DummyBase {}
    public static class _567 extends DummyBase {}
    public static class _568 extends DummyBase {}
    public static class _569 extends DummyBase {}
    public static class _570 extends DummyBase {}
    public static class _571 extends DummyBase {}
    public static class _572 extends DummyBase {}
    public static class _573 extends DummyBase {}
    public static class _574 extends DummyBase {}
    public static class _575 extends DummyBase {}
    public static class _576 extends DummyBase {}
    public static class _577 extends DummyBase {}
    public static class _578 extends DummyBase {}
    public static class _579 extends DummyBase {}
    public static class _580 extends DummyBase {}
    public static class _581 extends DummyBase {}
    public static class _582 extends DummyBase {}
    public static class _583 extends DummyBase {}
    public static class _584 extends DummyBase {}
    public static class _585 extends DummyBase {}
    public static class _586 extends DummyBase {}
    public static class _587 extends DummyBase {}
    public static class _588 extends DummyBase {}
    public static class _589 extends DummyBase {}
    public static class _590 extends DummyBase {}
    public static class _591 extends DummyBase {}
    public static class _592 extends DummyBase {}
    public static class _593 extends DummyBase {}
    public static class _594 extends DummyBase {}
    public static class _595 extends DummyBase {}
    public static class _596 extends DummyBase {}
    public static class _597 extends DummyBase {}
    public static class _598 extends DummyBase {}
    public static class _599 extends DummyBase {}
    public static class _600 extends DummyBase {}
    public static class _601 extends DummyBase {}
    public static class _602 extends DummyBase {}
    public static class _603 extends DummyBase {}
    public static class _604 extends DummyBase {}
    public static class _605 extends DummyBase {}
    public static class _606 extends DummyBase {}
    public static class _607 extends DummyBase {}
    public static class _608 extends DummyBase {}
    public static class _609 extends DummyBase {}
    public static class _610 extends DummyBase {}
    public static class _611 extends DummyBase {}
    public static class _612 extends DummyBase {}
    public static class _613 extends DummyBase {}
    public static class _614 extends DummyBase {}
    public static class _615 extends DummyBase {}
    public static class _616 extends DummyBase {}
    public static class _617 extends DummyBase {}
    public static class _618 extends DummyBase {}
    public static class _619 extends DummyBase {}
    public static class _620 extends DummyBase {}
    public static class _621 extends DummyBase {}
    public static class _622 extends DummyBase {}
    public static class _623 extends DummyBase {}
    public static class _624 extends DummyBase {}
    public static class _625 extends DummyBase {}
    public static class _626 extends DummyBase {}
    public static class _627 extends DummyBase {}
    public static class _628 extends DummyBase {}
    public static class _629 extends DummyBase {}
    public static class _630 extends DummyBase {}
    public static class _631 extends DummyBase {}
    public static class _632 extends DummyBase {}
    public static class _633 extends DummyBase {}
    public static class _634 extends DummyBase {}
    public static class _635 extends DummyBase {}
    public static class _636 extends DummyBase {}
    public static class _637 extends DummyBase {}
    public static class _638 extends DummyBase {}
    public static class _639 extends DummyBase {}
    public static class _640 extends DummyBase {}
    public static class _641 extends DummyBase {}
    public static class _642 extends DummyBase {}
    public static class _643 extends DummyBase {}
    public static class _644 extends DummyBase {}
    public static class _645 extends DummyBase {}
    public static class _646 extends DummyBase {}
    public static class _647 extends DummyBase {}
    public static class _648 extends DummyBase {}
    public static class _649 extends DummyBase {}
    public static class _650 extends DummyBase {}
    public static class _651 extends DummyBase {}
    public static class _652 extends DummyBase {}
    public static class _653 extends DummyBase {}
    public static class _654 extends DummyBase {}
    public static class _655 extends DummyBase {}
    public static class _656 extends DummyBase {}
    public static class _657 extends DummyBase {}
    public static class _658 extends DummyBase {}
    public static class _659 extends DummyBase {}
    public static class _660 extends DummyBase {}
    public static class _661 extends DummyBase {}
    public static class _662 extends DummyBase {}
    public static class _663 extends DummyBase {}
    public static class _664 extends DummyBase {}
    public static class _665 extends DummyBase {}
    public static class _666 extends DummyBase {}
    public static class _667 extends DummyBase {}
    public static class _668 extends DummyBase {}
    public static class _669 extends DummyBase {}
    public static class _670 extends DummyBase {}
    public static class _671 extends DummyBase {}
    public static class _672 extends DummyBase {}
    public static class _673 extends DummyBase {}
    public static class _674 extends DummyBase {}
    public static class _675 extends DummyBase {}
    public static class _676 extends DummyBase {}
    public static class _677 extends DummyBase {}
    public static class _678 extends DummyBase {}
    public static class _679 extends DummyBase {}
    public static class _680 extends DummyBase {}
    public static class _681 extends DummyBase {}
    public static class _682 extends DummyBase {}
    public static class _683 extends DummyBase {}
    public static class _684 extends DummyBase {}
    public static class _685 extends DummyBase {}
    public static class _686 extends DummyBase {}
    public static class _687 extends DummyBase {}
    public static class _688 extends DummyBase {}
    public static class _689 extends DummyBase {}
    public static class _690 extends DummyBase {}
    public static class _691 extends DummyBase {}
    public static class _692 extends DummyBase {}
    public static class _693 extends DummyBase {}
    public static class _694 extends DummyBase {}
    public static class _695 extends DummyBase {}
    public static class _696 extends DummyBase {}
    public static class _697 extends DummyBase {}
    public static class _698 extends DummyBase {}
    public static class _699 extends DummyBase {}
    public static class _700 extends DummyBase {}
    public static class _701 extends DummyBase {}
    public static class _702 extends DummyBase {}
    public static class _703 extends DummyBase {}
    public static class _704 extends DummyBase {}
    public static class _705 extends DummyBase {}
    public static class _706 extends DummyBase {}
    public static class _707 extends DummyBase {}
    public static class _708 extends DummyBase {}
    public static class _709 extends DummyBase {}
    public static class _710 extends DummyBase {}
    public static class _711 extends DummyBase {}
    public static class _712 extends DummyBase {}
    public static class _713 extends DummyBase {}
    public static class _714 extends DummyBase {}
    public static class _715 extends DummyBase {}
    public static class _716 extends DummyBase {}
    public static class _717 extends DummyBase {}
    public static class _718 extends DummyBase {}
    public static class _719 extends DummyBase {}
    public static class _720 extends DummyBase {}
    public static class _721 extends DummyBase {}
    public static class _722 extends DummyBase {}
    public static class _723 extends DummyBase {}
    public static class _724 extends DummyBase {}
    public static class _725 extends DummyBase {}
    public static class _726 extends DummyBase {}
    public static class _727 extends DummyBase {}
    public static class _728 extends DummyBase {}
    public static class _729 extends DummyBase {}
    public static class _730 extends DummyBase {}
    public static class _731 extends DummyBase {}
    public static class _732 extends DummyBase {}
    public static class _733 extends DummyBase {}
    public static class _734 extends DummyBase {}
    public static class _735 extends DummyBase {}
    public static class _736 extends DummyBase {}
    public static class _737 extends DummyBase {}
    public static class _738 extends DummyBase {}
    public static class _739 extends DummyBase {}
    public static class _740 extends DummyBase {}
    public static class _741 extends DummyBase {}
    public static class _742 extends DummyBase {}
    public static class _743 extends DummyBase {}
    public static class _744 extends DummyBase {}
    public static class _745 extends DummyBase {}
    public static class _746 extends DummyBase {}
    public static class _747 extends DummyBase {}
    public static class _748 extends DummyBase {}
    public static class _749 extends DummyBase {}
    public static class _750 extends DummyBase {}
    public static class _751 extends DummyBase {}
    public static class _752 extends DummyBase {}
    public static class _753 extends DummyBase {}
    public static class _754 extends DummyBase {}
    public static class _755 extends DummyBase {}
    public static class _756 extends DummyBase {}
    public static class _757 extends DummyBase {}
    public static class _758 extends DummyBase {}
    public static class _759 extends DummyBase {}
    public static class _760 extends DummyBase {}
    public static class _761 extends DummyBase {}
    public static class _762 extends DummyBase {}
    public static class _763 extends DummyBase {}
    public static class _764 extends DummyBase {}
    public static class _765 extends DummyBase {}
    public static class _766 extends DummyBase {}
    public static class _767 extends DummyBase {}
    public static class _768 extends DummyBase {}
    public static class _769 extends DummyBase {}
    public static class _770 extends DummyBase {}
    public static class _771 extends DummyBase {}
    public static class _772 extends DummyBase {}
    public static class _773 extends DummyBase {}
    public static class _774 extends DummyBase {}
    public static class _775 extends DummyBase {}
    public static class _776 extends DummyBase {}
    public static class _777 extends DummyBase {}
    public static class _778 extends DummyBase {}
    public static class _779 extends DummyBase {}
    public static class _780 extends DummyBase {}
    public static class _781 extends DummyBase {}
    public static class _782 extends DummyBase {}
    public static class _783 extends DummyBase {}
    public static class _784 extends DummyBase {}
    public static class _785 extends DummyBase {}
    public static class _786 extends DummyBase {}
    public static class _787 extends DummyBase {}
    public static class _788 extends DummyBase {}
    public static class _789 extends DummyBase {}
    public static class _790 extends DummyBase {}
    public static class _791 extends DummyBase {}
    public static class _792 extends DummyBase {}
    public static class _793 extends DummyBase {}
    public static class _794 extends DummyBase {}
    public static class _795 extends DummyBase {}
    public static class _796 extends DummyBase {}
    public static class _797 extends DummyBase {}
    public static class _798 extends DummyBase {}
    public static class _799 extends DummyBase {}
    public static class _800 extends DummyBase {}
    public static class _801 extends DummyBase {}
    public static class _802 extends DummyBase {}
    public static class _803 extends DummyBase {}
    public static class _804 extends DummyBase {}
    public static class _805 extends DummyBase {}
    public static class _806 extends DummyBase {}
    public static class _807 extends DummyBase {}
    public static class _808 extends DummyBase {}
    public static class _809 extends DummyBase {}
    public static class _810 extends DummyBase {}
    public static class _811 extends DummyBase {}
    public static class _812 extends DummyBase {}
    public static class _813 extends DummyBase {}
    public static class _814 extends DummyBase {}
    public static class _815 extends DummyBase {}
    public static class _816 extends DummyBase {}
    public static class _817 extends DummyBase {}
    public static class _818 extends DummyBase {}
    public static class _819 extends DummyBase {}
    public static class _820 extends DummyBase {}
    public static class _821 extends DummyBase {}
    public static class _822 extends DummyBase {}
    public static class _823 extends DummyBase {}
    public static class _824 extends DummyBase {}
    public static class _825 extends DummyBase {}
    public static class _826 extends DummyBase {}
    public static class _827 extends DummyBase {}
    public static class _828 extends DummyBase {}
    public static class _829 extends DummyBase {}
    public static class _830 extends DummyBase {}
    public static class _831 extends DummyBase {}
    public static class _832 extends DummyBase {}
    public static class _833 extends DummyBase {}
    public static class _834 extends DummyBase {}
    public static class _835 extends DummyBase {}
    public static class _836 extends DummyBase {}
    public static class _837 extends DummyBase {}
    public static class _838 extends DummyBase {}
    public static class _839 extends DummyBase {}
    public static class _840 extends DummyBase {}
    public static class _841 extends DummyBase {}
    public static class _842 extends DummyBase {}
    public static class _843 extends DummyBase {}
    public static class _844 extends DummyBase {}
    public static class _845 extends DummyBase {}
    public static class _846 extends DummyBase {}
    public static class _847 extends DummyBase {}
    public static class _848 extends DummyBase {}
    public static class _849 extends DummyBase {}
    public static class _850 extends DummyBase {}
    public static class _851 extends DummyBase {}
    public static class _852 extends DummyBase {}
    public static class _853 extends DummyBase {}
    public static class _854 extends DummyBase {}
    public static class _855 extends DummyBase {}
    public static class _856 extends DummyBase {}
    public static class _857 extends DummyBase {}
    public static class _858 extends DummyBase {}
    public static class _859 extends DummyBase {}
    public static class _860 extends DummyBase {}
    public static class _861 extends DummyBase {}
    public static class _862 extends DummyBase {}
    public static class _863 extends DummyBase {}
    public static class _864 extends DummyBase {}
    public static class _865 extends DummyBase {}
    public static class _866 extends DummyBase {}
    public static class _867 extends DummyBase {}
    public static class _868 extends DummyBase {}
    public static class _869 extends DummyBase {}
    public static class _870 extends DummyBase {}
    public static class _871 extends DummyBase {}
    public static class _872 extends DummyBase {}
    public static class _873 extends DummyBase {}
    public static class _874 extends DummyBase {}
    public static class _875 extends DummyBase {}
    public static class _876 extends DummyBase {}
    public static class _877 extends DummyBase {}
    public static class _878 extends DummyBase {}
    public static class _879 extends DummyBase {}
    public static class _880 extends DummyBase {}
    public static class _881 extends DummyBase {}
    public static class _882 extends DummyBase {}
    public static class _883 extends DummyBase {}
    public static class _884 extends DummyBase {}
    public static class _885 extends DummyBase {}
    public static class _886 extends DummyBase {}
    public static class _887 extends DummyBase {}
    public static class _888 extends DummyBase {}
    public static class _889 extends DummyBase {}
    public static class _890 extends DummyBase {}
    public static class _891 extends DummyBase {}
    public static class _892 extends DummyBase {}
    public static class _893 extends DummyBase {}
    public static class _894 extends DummyBase {}
    public static class _895 extends DummyBase {}
    public static class _896 extends DummyBase {}
    public static class _897 extends DummyBase {}
    public static class _898 extends DummyBase {}
    public static class _899 extends DummyBase {}
    public static class _900 extends DummyBase {}
    public static class _901 extends DummyBase {}
    public static class _902 extends DummyBase {}
    public static class _903 extends DummyBase {}
    public static class _904 extends DummyBase {}
    public static class _905 extends DummyBase {}
    public static class _906 extends DummyBase {}
    public static class _907 extends DummyBase {}
    public static class _908 extends DummyBase {}
    public static class _909 extends DummyBase {}
    public static class _910 extends DummyBase {}
    public static class _911 extends DummyBase {}
    public static class _912 extends DummyBase {}
    public static class _913 extends DummyBase {}
    public static class _914 extends DummyBase {}
    public static class _915 extends DummyBase {}
    public static class _916 extends DummyBase {}
    public static class _917 extends DummyBase {}
    public static class _918 extends DummyBase {}
    public static class _919 extends DummyBase {}
    public static class _920 extends DummyBase {}
    public static class _921 extends DummyBase {}
    public static class _922 extends DummyBase {}
    public static class _923 extends DummyBase {}
    public static class _924 extends DummyBase {}
    public static class _925 extends DummyBase {}
    public static class _926 extends DummyBase {}
    public static class _927 extends DummyBase {}
    public static class _928 extends DummyBase {}
    public static class _929 extends DummyBase {}
    public static class _930 extends DummyBase {}
    public static class _931 extends DummyBase {}
    public static class _932 extends DummyBase {}
    public static class _933 extends DummyBase {}
    public static class _934 extends DummyBase {}
    public static class _935 extends DummyBase {}
    public static class _936 extends DummyBase {}
    public static class _937 extends DummyBase {}
    public static class _938 extends DummyBase {}
    public static class _939 extends DummyBase {}
    public static class _940 extends DummyBase {}
    public static class _941 extends DummyBase {}
    public static class _942 extends DummyBase {}
    public static class _943 extends DummyBase {}
    public static class _944 extends DummyBase {}
    public static class _945 extends DummyBase {}
    public static class _946 extends DummyBase {}
    public static class _947 extends DummyBase {}
    public static class _948 extends DummyBase {}
    public static class _949 extends DummyBase {}
    public static class _950 extends DummyBase {}
    public static class _951 extends DummyBase {}
    public static class _952 extends DummyBase {}
    public static class _953 extends DummyBase {}
    public static class _954 extends DummyBase {}
    public static class _955 extends DummyBase {}
    public static class _956 extends DummyBase {}
    public static class _957 extends DummyBase {}
    public static class _958 extends DummyBase {}
    public static class _959 extends DummyBase {}
    public static class _960 extends DummyBase {}
    public static class _961 extends DummyBase {}
    public static class _962 extends DummyBase {}
    public static class _963 extends DummyBase {}
    public static class _964 extends DummyBase {}
    public static class _965 extends DummyBase {}
    public static class _966 extends DummyBase {}
    public static class _967 extends DummyBase {}
    public static class _968 extends DummyBase {}
    public static class _969 extends DummyBase {}
    public static class _970 extends DummyBase {}
    public static class _971 extends DummyBase {}
    public static class _972 extends DummyBase {}
    public static class _973 extends DummyBase {}
    public static class _974 extends DummyBase {}
    public static class _975 extends DummyBase {}
    public static class _976 extends DummyBase {}
    public static class _977 extends DummyBase {}
    public static class _978 extends DummyBase {}
    public static class _979 extends DummyBase {}
    public static class _980 extends DummyBase {}
    public static class _981 extends DummyBase {}
    public static class _982 extends DummyBase {}
    public static class _983 extends DummyBase {}
    public static class _984 extends DummyBase {}
    public static class _985 extends DummyBase {}
    public static class _986 extends DummyBase {}
    public static class _987 extends DummyBase {}
    public static class _988 extends DummyBase {}
    public static class _989 extends DummyBase {}
    public static class _990 extends DummyBase {}
    public static class _991 extends DummyBase {}
    public static class _992 extends DummyBase {}
    public static class _993 extends DummyBase {}
    public static class _994 extends DummyBase {}
    public static class _995 extends DummyBase {}
    public static class _996 extends DummyBase {}
    public static class _997 extends DummyBase {}
    public static class _998 extends DummyBase {}
    public static class _999 extends DummyBase {}
    public static class _1000 extends DummyBase {}

}
